version: '3'

services:
  web:
    build: ./
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py makemigrations &&
             python manage.py migrate"
    ports:
      - 8000:8000
    depends_on:
      - postgres

  postgres:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres_DB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn stocks_products.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code/static
    depends_on:
      - postgres

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
    restart: unless-stopped
