version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: netology_stocks_products
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn logistic.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    depends_on:
      - postgres

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - backend